# Site settings
title: Yeara Kozlov | Computer Graphics Lab - ETH Zürich,  Disney Research Zürich


email: yeara.kozlov [at] disneyresearch.com

url: http://www.yearakozlov.com

timezone : Europe/Berlin
encoding : utf-8

# Build settings
markdown: kramdown


exclude: ["README.md"]

permalink: pretty

sass:
  style: compressed